apiVersion: v1
kind: Service
metadata:
  name: frontend_service
spec:
  selector:
    name: frontend
  type: NodePort
  ports:
  - port: 7000
    targetPort: 5000
    nodePort: 30039
    protocol: TCP
